apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  known_devices.yaml: |

  automations.yaml: |

  ui-lovelace.yaml: |

  configuration.yaml: |
    homeassistant:
      # Name of the location where Home Assistant is running
      name: Home
      # Location required to calculate the time the sun rises and sets
      latitude: 54.03272894278802
      longitude: 11.665036436474116
      # Impacts weather/sunrise data (altitude above sea level in meters)
      elevation: 1
      # metric for Metric, imperial for Imperial
      unit_system: metric
      time_zone: Europe/Berlin
      
      # Enables the frontend
    frontend:

    # Enables configuration UI
    config:

    #Enable support for mobile client
    mobile_app:

    lovelace:
      mode: storage

    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    http:
      server_port: 8123
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.244.1.0/24
      login_attempts_threshold: 5
        
    light:
      - platform: mqtt
        name: "Große Schlafzimmerlampe"
        state_topic: "stat/sonoff_fan/RESULT"
        value_template: "{{ value_json.POWER1 }}"
        command_topic: "cmnd/sonoff_fan/POWER1"
        availability_topic: "tele/sonoff_fan/LWT"
        qos: 1
        payload_on: "ON"
        payload_off: "OFF"
        payload_available: "Online"
        payload_not_available: "Offline"
        retain: false
