apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tom.ritmeier@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
