apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment-test
  namespace: home-assistant
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red-test
  template:
    metadata:
      labels:
        app: node-red-test
    spec:
      priorityClassName: ignore-me
      initContainers:
        - name: data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name:  local-tmp
              mountPath: /data/
      containers:
        - name: node-red-test
          image: nodered/node-red-docker:rpi
          ports:
            - containerPort: 1880
          resources:
            requests:
              memory: 75Mi
            limits:
              memory: 150Mi
          volumeMounts:
            - name: local-tmp
              mountPath: /data/
            - mountPath: /data/settings.js
              name: node-red-settings-js
              subPath: settings.js
            - mountPath: /etc/localtime
              name: tz-europe
      volumes:
        - name: node-red-settings-js
          configMap:
            defaultMode: 420
            name: node-red-settings-js-map
        - name: local-tmp
          hostPath:
            path: /tmp/node-red-test
        - name: tz-europe
          hostPath:
            path: /usr/share/zoneinfo/Europe/Berlin
---
kind: Service
apiVersion: v1
metadata:
  name: node-red-service-test
  namespace: home-assistant
spec:
  selector:
    app: node-red-test
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      name: node-red-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-red-ingress-test
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: node-red-test.cluster
      http:
        paths:
          - path: /
            backend:
              serviceName: node-red-service-test
              servicePort: 1880
