apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-update-moyapro
  namespace: home-assistant
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          priorityClassName: high
          containers:
          - name: dns-update
            image: evns/rpi-utilities
            resources:
              requests:
                memory: 5Mi
              limits:
                memory: 15Mi
            command: [ "/bin/sh"]
            args: ["-c", "curl --verbose https://www.duckdns.org/update?domains=${DNS_UPDATE_DOMAIN}\\&token=${DNS_UPDATE_TOKEN}\\&verbose=true"]
            env:
            - name: DNS_UPDATE_DOMAIN
              value: moyapro
            - name: DNS_UPDATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: duckdns
                  key: token
          restartPolicy: Never
