apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
  namespace: home-assistant
data:
  configuration.yaml: |
    # Required: Home Assistant integration (MQTT discovery) (default: false)
    homeassistant: true

    # Required: allow new devices to join.
    # WARNING: Disable this after all devices have been paired! (default: false)
    permit_join: false

    # Required: MQTT settings
    mqtt:
      # Required: MQTT base topic for Zigbee2MQTT MQTT messages
      base_topic: zigbee2mqtt
      # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
      server: 'mqtt://192.168.1.101:31883'
      # Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
      #ca: '/etc/ssl/mqtt-ca.crt'
      # Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
      #key: '/etc/ssl/mqtt-client.key'
      #cert: '/etc/ssl/mqtt-client.crt'
      # Optional: MQTT server authentication user (default: nothing)
      user: homeassistant
      # Optional: MQTT server authentication password (default: nothing)
      password: password
      # Optional: MQTT client ID (default: nothing)
      client_id: 'zigbee2mqtt'
      # Optional: disable self-signed SSL certificates (default: true)
      #reject_unauthorized: true
      # Optional: Include device information to mqtt messages (default: false)
      include_device_information: true
      # Optional: MQTT keepalive in seconds (default: 60)
      keepalive: 300
      # Optional: MQTT protocol version (default: 4), set this to 5 if you
      # use the 'retention' device specific configuration
      version: 4

    # Required: serial settings
    serial:
      # Required: location of the adapter (e.g. CC2531).
      # To autodetect the port, set 'port: null'.
      port: /dev/ttyACM0
      # Optional: disable LED of the adapter if supported (default: false)
      disable_led: false
      # Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz)
      #adapter: null
    loglevel: debug
    log_directory: /tmp/log/zigbee2mqtt/%TIMESTAMP%
    # Optional: Log file name, can also contain timestamp, e.g.: zigbee2mqtt_%TIMESTAMP%.log (default: shown below)
    log_file: zigbee2mqtt.log
    # Optional: Log rotation (default: shown below)
    log_rotation: true
    # Optional: Output location of the log (default: shown below), leave empty to supress logging (log_output: [])
    # possible options: 'console', 'file', 'syslog'
    log_output:
        - console

    devices:
      - new_devices.yaml # new devices will be written here
      - preconfigured_devices.yaml # shoulde be provided by configmap


  preconfigured_devices.yaml: |
    '0x00158d00053d3bc2':
      friendly_name: 'Wohnzimmer Thermostat'
    '0x00124b002228ec04':
      friendly_name: 'Balkontür'
    '0x00158d000577bc9c':
      friendly_name: 'Waschmaschine Vibration'
    '0x00158d0002b7a1ee':
      friendly_name: 'Klingel'


