apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt-deployment
  namespace: home-assistant
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      priorityClassName: default
      nodeSelector:
        kubernetes.io/hostname: pi-worker-1
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.21.2
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/data/configuration.yaml
              subPath: configuration.yaml
            - name: config-volume
              mountPath: /app/data/preconfigured_devices.yaml
              subPath: preconfigured_devices.yaml
            - name: semi-persistant-config
              mountPath: /app/data
            - name: log-volume
              mountPath: /app/data/log
            - name: devzigbeestick0
              mountPath: /dev/ttyACM0
          securityContext:
            privileged: true
      volumes:
        - name: config-volume
          configMap:
            name: zigbee2mqtt-config
        - name: semi-persistant-config
          hostPath:
            path: /tmp/zigbee2mqtt/data
        - name: log-volume
          hostPath:
            path: /tmp/zigbee2mqtt/log
        - name: devzigbeestick0
          hostPath:
            path: /dev/ttyACM0
