apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt-deployment
  namespace: home-assistant
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      priorityClassName: high
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.16.1
          resources:
            requests:
              memory: 1Mi
            limits:
              memory: 10Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/data
      volumes:
        - name: config-volume
          configMap:
            name: zigbee2mqtt-config
