apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-flows-map
  namespace: home-assistant
data:
  flows.json: |
    [
      {
        "id": "1fe996d2.26ec49",
        "type": "tab",
        "label": "TV",
        "disabled": false,
        "info": ""
      },
      {
        "id": "6052f386.ba7e0c",
        "type": "subflow",
        "name": "Blink LED",
        "info": "",
        "category": "",
        "in": [
          {
            "x": 50,
            "y": 30,
            "wires": [
              {
                "id": "61f37b44.a5c344"
              },
              {
                "id": "7f30dd01.e7b344"
              }
            ]
          }
        ],
        "out": []
      },
      {
        "id": "2b61e807.3ed978",
        "type": "bravia-tv",
        "z": "",
        "name": "Sony Bravia",
        "host": "192.168.1.111",
        "port": "80",
        "psk": "Superteam17"
      },
      {
        "id": "9e0e9c3b.c8747",
        "type": "mqtt-broker",
        "z": "",
        "name": "NodeRedMttq",
        "broker": "localhost",
        "port": "1883",
        "clientid": "node red mqtt incoming",
        "usetls": false,
        "compatmode": false,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "welcome to mttq broker test",
        "birthQos": "0",
        "birthPayload": "the welcome payload",
        "closeTopic": "Bye!",
        "closeQos": "0",
        "closePayload": "ByeMessage",
        "willTopic": "Disconnected",
        "willQos": "0",
        "willPayload": "disconnected payload"
      },
      {
        "id": "47068ed0.8db12",
        "type": "http in",
        "z": "1fe996d2.26ec49",
        "name": "PC on",
        "url": "/notify/pc/on",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 110,
        "y": 320,
        "wires": [
          [
            "9bd88983.385158",
            "110aa7c0.2cf2f8",
            "5ae00df7.1c3df4"
          ]
        ]
      },
      {
        "id": "74c6d8f.9790c28",
        "type": "bravia-ircc",
        "z": "1fe996d2.26ec49",
        "tv": "2b61e807.3ed978",
        "ircc": "Hdmi4",
        "name": "Switch to HDMI 4",
        "x": 1184.5,
        "y": 313,
        "wires": []
      },
      {
        "id": "9bd88983.385158",
        "type": "http response",
        "z": "1fe996d2.26ec49",
        "name": "RespondOK",
        "statusCode": "200",
        "headers": {},
        "x": 330,
        "y": 440,
        "wires": []
      },
      {
        "id": "bf3375be.eaeae8",
        "type": "bravia-ircc",
        "z": "1fe996d2.26ec49",
        "tv": "2b61e807.3ed978",
        "ircc": "Home",
        "name": "Switch to Home",
        "x": 340,
        "y": 80,
        "wires": []
      },
      {
        "id": "2cf7aebe.8d50a2",
        "type": "http in",
        "z": "1fe996d2.26ec49",
        "name": "PC off",
        "url": "/notify/pc/off",
        "method": "get",
        "upload": false,
        "swaggerDoc": "",
        "x": 110,
        "y": 80,
        "wires": [
          [
            "bf3375be.eaeae8",
            "32af12b6.cc17ce",
            "64026a33.d99554"
          ]
        ]
      },
      {
        "id": "9e70ab8d.c913a8",
        "type": "bravia-api",
        "z": "6052f386.ba7e0c",
        "tv": "2b61e807.3ed978",
        "method": "system:1.1:setLEDIndicatorStatus",
        "payload": "{\"mode\":\"Dark\", \"status\":\"true\"}",
        "name": "LED Dark",
        "x": 395,
        "y": 120,
        "wires": [
          []
        ]
      },
      {
        "id": "61f37b44.a5c344",
        "type": "delay",
        "z": "6052f386.ba7e0c",
        "name": "",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 227,
        "y": 121,
        "wires": [
          [
            "9e70ab8d.c913a8"
          ]
        ]
      },
      {
        "id": "7f30dd01.e7b344",
        "type": "bravia-api",
        "z": "6052f386.ba7e0c",
        "tv": "2b61e807.3ed978",
        "method": "system:1.1:setLEDIndicatorStatus",
        "payload": "{\"mode\":\"AutoBrightnessAdjust\", \"status\":\"true\"}",
        "name": "LED auto",
        "x": 395,
        "y": 60,
        "wires": [
          []
        ]
      },
      {
        "id": "32af12b6.cc17ce",
        "type": "subflow:6052f386.ba7e0c",
        "z": "1fe996d2.26ec49",
        "name": "",
        "x": 320,
        "y": 200,
        "wires": []
      },
      {
        "id": "64026a33.d99554",
        "type": "http response",
        "z": "1fe996d2.26ec49",
        "name": "RespondOK",
        "statusCode": "200",
        "headers": {},
        "x": 330,
        "y": 140,
        "wires": []
      },
      {
        "id": "110aa7c0.2cf2f8",
        "type": "subflow:6052f386.ba7e0c",
        "z": "1fe996d2.26ec49",
        "name": "",
        "x": 320,
        "y": 380,
        "wires": []
      },
      {
        "id": "66e9aa61.195c84",
        "type": "bravia-api",
        "z": "1fe996d2.26ec49",
        "tv": "2b61e807.3ed978",
        "method": "system:1.0:setPowerStatus",
        "payload": "{\"status\": true}",
        "name": "activate TV",
        "x": 910,
        "y": 360,
        "wires": [
          [
            "2c0b6f12.18edd"
          ]
        ]
      },
      {
        "id": "5ae00df7.1c3df4",
        "type": "bravia-api",
        "z": "1fe996d2.26ec49",
        "tv": "2b61e807.3ed978",
        "method": "system:1.0:getPowerStatus",
        "payload": "",
        "name": "Power status?",
        "x": 340,
        "y": 320,
        "wires": [
          [
            "1bd936c8.d51339",
            "33acf943.975486"
          ]
        ]
      },
      {
        "id": "1bd936c8.d51339",
        "type": "switch",
        "z": "1fe996d2.26ec49",
        "name": "Power status active?",
        "property": "payload.status",
        "propertyType": "msg",
        "rules": [
          {
            "t": "eq",
            "v": "active",
            "vt": "str"
          },
          {
            "t": "neq",
            "v": "active",
            "vt": "str"
          }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 600,
        "y": 320,
        "wires": [
          [
            "74c6d8f.9790c28",
            "33acf943.975486"
          ],
          [
            "6e6fb2e2.50e86c",
            "66e9aa61.195c84",
            "33acf943.975486"
          ]
        ]
      },
      {
        "id": "6e6fb2e2.50e86c",
        "type": "delay",
        "z": "1fe996d2.26ec49",
        "name": "",
        "pauseType": "delay",
        "timeout": "5",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 900,
        "y": 480,
        "wires": [
          [
            "74c6d8f.9790c28",
            "33acf943.975486"
          ]
        ]
      },
      {
        "id": "2c0b6f12.18edd",
        "type": "http response",
        "z": "1fe996d2.26ec49",
        "name": "RespondOK",
        "statusCode": "200",
        "headers": {},
        "x": 910,
        "y": 420,
        "wires": []
      },
      {
        "id": "33acf943.975486",
        "type": "debug",
        "z": "1fe996d2.26ec49",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 910,
        "y": 160,
        "wires": []
      },
      {
        "id": "d4414c1b.6097e",
        "type": "inject",
        "z": "1fe996d2.26ec49",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 100,
        "y": 240,
        "wires": [
          [
            "5ae00df7.1c3df4"
          ]
        ]
      },
      {
        "id": "6ab61066.533a4",
        "type": "inject",
        "z": "1fe996d2.26ec49",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 160,
        "wires": [
          [
            "bf3375be.eaeae8"
          ]
        ]
      }
    ,
    {
        "id": "2b4b06d4.23cfba",
        "type": "tab",
        "label": "Switch PC",
        "disabled": false,
        "info": ""
      },
      {
        "id": "75afc520.37091c",
        "type": "mqtt in",
        "z": "2b4b06d4.23cfba",
        "name": "pc switch ",
        "topic": "wohnzimmer/pc/command",
        "qos": "2",
        "datatype": "utf8",
        "broker": "5fc14613.225b28",
        "x": 191,
        "y": 516,
        "wires": [
          [
            "52eef1c4.e8acb",
            "1bb17fa8.c9e2b"
          ]
        ]
      },
      {
        "id": "c8a411ce.29091",
        "type": "mqtt out",
        "z": "2b4b06d4.23cfba",
        "name": "status out",
        "topic": "wohnzimmer/pc/status",
        "qos": "",
        "retain": "false",
        "broker": "5fc14613.225b28",
        "x": 633,
        "y": 319,
        "wires": []
      },
      {
        "id": "52eef1c4.e8acb",
        "type": "function",
        "z": "2b4b06d4.23cfba",
        "name": "forward status to status topic",
        "func": "\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 370,
        "y": 320,
        "wires": [
          [
            "c8a411ce.29091"
          ]
        ]
      },
      {
        "id": "7cf688d1.4fc408",
        "type": "wake on lan",
        "z": "2b4b06d4.23cfba",
        "mac": "00:19:99:bf:43:c7",
        "host": "192.168.1.19",
        "name": "Wake pc",
        "x": 557,
        "y": 433,
        "wires": []
      },
      {
        "id": "1bb17fa8.c9e2b",
        "type": "switch",
        "z": "2b4b06d4.23cfba",
        "name": "on/off",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
          {
            "t": "eq",
            "v": "on",
            "vt": "str"
          },
          {
            "t": "eq",
            "v": "off",
            "vt": "str"
          }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 391,
        "y": 517,
        "wires": [
          [
            "7cf688d1.4fc408",
            "eb3b9ec.2ee926"
          ],
          [
            "855ba09d.ef732"
          ]
        ]
      },
      {
        "id": "eb3b9ec.2ee926",
        "type": "debug",
        "z": "2b4b06d4.23cfba",
        "name": "wake log",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "'wake up pc'",
        "targetType": "jsonata",
        "x": 547,
        "y": 390,
        "wires": []
      },
      {
        "id": "855ba09d.ef732",
        "type": "debug",
        "z": "2b4b06d4.23cfba",
        "name": "Shutdown mqtt message is handled on device itself using https://github.com/denschu/mqtt-exec",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "'shut down pc'",
        "targetType": "jsonata",
        "x": 550,
        "y": 582,
        "wires": []
      },
      {
        "id": "5fc14613.225b28",
        "type": "mqtt-broker",
        "z": "",
        "name": "",
        "broker": "192.168.1.101",
        "port": "31883",
        "clientid": "node-red",
        "usetls": false,
        "compatmode": false,
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "willTopic": "",
        "willQos": "0",
        "willPayload": ""
      },
      {
          "id": "56901e89.3e15f",
          "type": "tab",
          "label": "Schlafzimmer",
          "disabled": false,
          "info": ""
      },
      {
          "id": "446b4e4d.cf46b",
          "type": "mqtt in",
          "z": "56901e89.3e15f",
          "name": "",
          "topic": "stat/sonoff-schlafzimmer-wand/POWER2",
          "qos": "2",
          "datatype": "auto",
          "broker": "7b794628.f84f38",
          "x": 240,
          "y": 120,
          "wires": [
              [
                  "3d89c906.ddb936"
              ]
          ]
      },
      {
          "id": "3d89c906.ddb936",
          "type": "mqtt out",
          "z": "56901e89.3e15f",
          "name": "",
          "topic": "cmnd/sonoff/POWER",
          "qos": "2",
          "retain": "true",
          "broker": "7b794628.f84f38",
          "x": 580,
          "y": 120,
          "wires": []
      },
      {
          "id": "7b794628.f84f38",
          "type": "mqtt-broker",
          "z": "",
          "name": "mqttS",
          "broker": "192.168.1.101",
          "port": "31883",
          "clientid": "node-red-test",
          "usetls": false,
          "compatmode": true,
          "keepalive": "60",
          "cleansession": true,
          "birthTopic": "",
          "birthQos": "0",
          "birthPayload": "",
          "closeTopic": "",
          "closeQos": "0",
          "closePayload": "",
          "willTopic": "",
          "willQos": "0",
          "willPayload": ""
      }
    ]

