apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
  namespace: home-assistant
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      priorityClassName: high
      initContainers:
        - name: data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: persistence
              mountPath: /data/
      containers:
        - name: node-red
          image: nodered/node-red:1.1.3
          ports:
            - containerPort: 1880
          resources:
            requests:
              memory: 75Mi
            limits:
              memory: 150Mi #increase to allow installation of additional nodes (out of memory otherwise)
          volumeMounts:
            - name: persistence
              mountPath: /data/
            - mountPath: /data/settings.js
              name: node-red-settings-js
              subPath: settings.js
            - mountPath: /data/flows.json
              name: node-red-flows
              subPath: flows.json
            - mountPath: /etc/localtime
              name: tz-europe
      volumes:
        - name: node-red-settings-js
          configMap:
            defaultMode: 420
            name: node-red-settings-js-map
        - name: node-red-flows
          configMap:
            defaultMode: 420
            name: node-red-flows-map
        - name: persistence
          persistentVolumeClaim:
            claimName: nas-persitant-volume-claim-node-red
        - name: tz-europe
          hostPath:
            path: /usr/share/zoneinfo/Europe/Berlin
---
kind: Service
apiVersion: v1
metadata:
  name: node-red-service
  namespace: home-assistant
spec:
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      name: node-red
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-red-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: node-red.cluster
      http:
        paths:
          - path: /
            backend:
              serviceName: node-red-service
              servicePort: 1880
