apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: home-assistant
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tom.ritmeier@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - dns01:
          duckdns:
            apiTokenSecretRef:
              name: duckdns-api-key
              key: data
