apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-https-cfg
  namespace: home-assistant
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [providers.kubernetesIngress]
    [api]
        dashboard = true
        insecure = true
    [accessLog]
    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
      address = ":443"
  
    [certificatesResolvers.myresolver.acme]
        email = "tom.ritmeier@gmail.com"
        storage = "acme.json"
      [certificatesResolvers.myresolver.acme.httpChallenge]
        entryPoint = "http"
    
    
    
    # Enable ACME (Let's Encrypt): automatic SSL.
    [acme]
    
    # Email address used for registration.
    #
    # Required
    #
      email = "tom.ritmeier@gmail.com"
      
      # File or key used for certificates storage.
      #
      # Required
      #
      storage = "acme.json"
      # or `storage = "traefik/acme/account"` if using KV store.
      
      # Entrypoint to proxy acme apply certificates to.
      #
      # Required
      #
      entryPoint = "https"
      
      # If true, display debug log messages from the acme client library.
      #
       acmeLogging = true
      
      # Deprecated. Enable on demand certificate generation.
      #
      # Optional
      # Default: false
      #
      # onDemand = true
      
      # Enable certificate generation on frontends host rules.
      #
      # Optional
      # Default: false
      #
      # onHostRule = true
      
      # CA server to use.
      # Uncomment the line to use Let's Encrypt's staging server,
      # leave commented to go to prod.
      #
      # Optional
      # Default: "https://acme-v02.api.letsencrypt.org/directory"
      #
      # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      
      # Preferred chain to use.
      #
      # Optional
      # Default: empty
      #
      preferredChain = "ISRG Root X1"
    
    # KeyType to use.
    #
    # Optional
    # Default: "RSA4096"
    #
    # Available values : "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192"
    #
    # KeyType = "RSA4096"
    
    # Use a TLS-ALPN-01 ACME challenge.
    #
    # Optional (but recommended)
    #
    #  [acme.tlsChallenge]
    
    # Use a HTTP-01 ACME challenge.
    #
    # Optional
    #
     [acme.httpChallenge]
     # entrypoint for http challenge
     entryPoint = "http"
    
    # Domains list.
    # Only domains defined here can generate wildcard certificates.
    # The certificates for these domains are negotiated at traefik startup only.
    #
     [[acme.domains]]
       main = "moyapro.duckdns.org"
     [[acme.domains]]
       main = "moyaprointern.duckdns.org"
     [[acme.domains]]
       main = "traefik.dashboard.local"
        
        
        
    
    # traefik.toml
#    defaultEntryPoints = ["http","https"]
#    [entryPoints.http]
#      address = ":80"
#      http.redirections.entryPoint.to = "https"
#      http.redirections.entryPoint.scheme = "https"
#      http.redirections.entryPoint.permanent = false
#      http.redirections.entryPoint.priority = 1
#      entryPoint = "https"
#    [entryPoints.https]
#      address = ":443"
#      [entryPoints.https.tls]
#    [acme]
#    email = "tom.ritmeier@gmail.com"
#    storage = "/etc/traefik/acme.json"
#    entryPoint = "https"
#    [acme.httpChallenge]
#        entryPoint = "http"
#    onDemand = true
#    onHostRule = true
#    caServer = "https://acme-v01.api.letsencrypt.org/directory"
#    [[acme.domains]]
#    main = "moyapro.duckdns.org"
