kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10.3
          args:
            - --api.insecure
            - --providers.kubernetesingress=true
            - --api.dashboard=true
            - --api.insecure=true
            - --log=true
            - --log.level=INFO
            - --accesslog=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.leresolver.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
            - --certificatesresolvers.leresolver.acme.email=<email> # <== Setting email for certs
            - --certificatesresolvers.leresolver.acme.storage=/data/acme.json # <== Defining acme file to store cert information
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: dashboard
              containerPort: 8080
