apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31966
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: web
  selector:
    app: traefik
