apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-https-cfg
  namespace: home-assistant
data:
  traefik.toml: |
    # traefik.toml
    defaultEntryPoints = ["http","https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.redirect]
      entryPoint = "https"
      [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
    [acme]
    email = "tom.ritmeier@gmail.com"
    storage = "/etc/traefik/acme.json"
    entryPoint = "https"
    [acme.httpChallenge]
        entryPoint = "http"
    onDemand = true
    onHostRule = true
    caServer = "https://acme-v01.api.letsencrypt.org/directory"
    [[acme.domains]]
    main = "moyapro.duckdns.org"
