apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high
value: 100
preemptionPolicy: Never
globalDefault: false
description: "Pods in this class are less likely to be preempted than the default"
