# mount this configmap as mosquitto.conf file in the /etc/mosquito into the mosquitto container
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
data:
  passwd: |
      password
  mosquitto.conf: |
    allow_anonymous false
    password_file /etc/mosquitto/passwd

    listener 1883 localhost