apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-https-cfg
  namespace: home-assistant
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    [providers.kubernetesIngress]
    [api]
    dashboard = true
    insecure = true
    #[accessLog]
    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
    address = ":443"
    
    
    # Enable ACME (Let's Encrypt): automatic SSL.
    [acme]
    entryPoint = "https"
    email = "tom.ritmeier@gmail.com"
    storage = "acme.json"
    acmeLogging = true
    logLevel = "DEBUG"
    onDemand = true #deprecated
    
    preferredChain = "ISRG Root X1"
    
    
    
    #[certificatesResolvers.letsencrypt.acme]
    #[certificatesResolvers.letsencrypt.acme.dnsChallenge]
    #provider = "duckdns"
    #delayBeforeCheck = 5
    #resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
    
    # Domains list.
    # Only domains defined here can generate wildcard certificates.
    # The certificates for these domains are negotiated at traefik startup only.
    #
    [[acme.domains]]
    main = "moyapro.duckdns.org"
#    [[acme.domains]]
#    main = "moyaprointern.duckdns.org"
#    [[acme.domains]]
#    main = "traefik.dashboard.local"
    
