apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  known_devices.yaml: |

  automations.yaml: |

  ui-lovelace.yaml: |

  configuration.yaml: |
    homeassistant:
      # Name of the location where Home Assistant is running
      name: Home
      # Location required to calculate the time the sun rises and sets
      latitude: 54.03272894278802
      longitude: 11.665036436474116
      # Impacts weather/sunrise data (altitude above sea level in meters)
      elevation: 1
      # metric for Metric, imperial for Imperial
      unit_system: metric
      time_zone: Europe/Berlin
      
      # Enables the frontend
    frontend:

    # Enables configuration UI
    config:

    #Enable support for mobile client
    mobile_app:

    lovelace:
      mode: storage

    http:
      server_port: 8123
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.244.0.0/16
      login_attempts_threshold: 5
        
    
    mqtt: !include_dir_merge_named lights/
