apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-light-config
  namespace: home-assistant
data:
  light.yaml: |
    light:
      - name: "Große Schlafzimmerlampe"
        unique_id : b89671b9-c4b5-46fe-9020-26d06b6de2d3
        state_topic: "stat/sonoff_fan/RESULT"
        command_topic: "cmnd/sonoff_fan/POWER1"
        optimistic: false
        availability_topic: "tele/sonoff_fan/LWT"
        payload_available: "Online"
        state_value_template: "{{ value_json.POWER1 }}"
        icon: mdi:ceiling-fan-light 
      - name: "Große Wohnzimmerlampe"
        unique_id : 2943c331-7780-490c-9c95-957b7aacc9b2
        state_topic: "stat/wohnzimmer_fan/RESULT"
        command_topic: "cmnd/wohnzimmer_fan/POWER1"
        optimistic: false
        availability_topic: "tele/wohnzimmer_fan/LWT"
        payload_available: "Online"
        state_value_template: "{{ value_json.POWER1 }}"
        icon: mdi:ceiling-fan-light
      - name: "Kleine Buerolampe"
        unique_id: 8af5002d-f113-4a3f-ab74-90ecb7ef94b0
        state_topic: "shellies/shellyplug-s-F8CC85/relay/0"
        command_topic: "shellies/shellyplug-s-F8CC85/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        availability_topic: "shellies/shellyplug-s-F8CC85/online"
        payload_available: "true"
        optimistic: false
      - name: "Schreibtisch Vintage"
        unique_id: cafdc15e-5137-456d-b606-1f55549572d1
        command_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/set"
        state_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        availability_topic: "shellies/ShellyVintage-98CDAC1EFF08/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:alarm-light
