apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-light-config
  namespace: home-assistant
data:
  light.yaml: |
    light:
      - name: "Große Schlafzimmerlampe"
        unique_id : b89671b9-c4b5-46fe-9020-26d06b6de2d3
        state_topic: "stat/sonoff_fan/RESULT"
        command_topic: "cmnd/sonoff_fan/POWER1"
        optimistic: false
        availability_topic: "tele/sonoff_fan/LWT"
        payload_available: "Online"
        state_value_template: "{{ value_json.POWER1 }}"
        icon: mdi:ceiling-fan-light 
      - name: "Große Wohnzimmerlampe"
        unique_id : 2943c331-7780-490c-9c95-957b7aacc9b2
        state_topic: "stat/wohnzimmer_fan/RESULT"
        command_topic: "cmnd/wohnzimmer_fan/POWER1"
        optimistic: false
        availability_topic: "tele/wohnzimmer_fan/LWT"
        payload_available: "Online"
        state_value_template: "{{ value_json.POWER1 }}"
        icon: mdi:ceiling-fan-light
      - name: "Kleine Buerolampe"
        unique_id: 8af5002d-f113-4a3f-ab74-90ecb7ef94b0
        state_topic: "shellies/shellyplug-s-F8CC85/relay/0"
        command_topic: "shellies/shellyplug-s-F8CC85/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        availability_topic: "shellies/shellyplug-s-F8CC85/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:moon-waning-crescent
      - name: "Schreibtisch Vintage"
        unique_id: cafdc15e-5137-456d-b606-1f55549572d1
        command_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyVintage-98CDAC1EFF08/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/ShellyVintage-98CDAC1EFF08/online"
        payload_available: "true"
        optimistic: false
      - name: "Grosse Buerolampe"
        unique_id: c7baed3d-017a-438c-b1f7-8c1d90f9d3f4
        command_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        color_temp_command_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/set"
        #temprange: 2700 - 6500
        color_temp_command_template: >-
          { temp: {{ (((((500 - value) / (500 - 153))) * (6500 - 2700)) + 2700) | round(0) }} }
        color_temp_state_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/status"
        color_temp_value_template: "{{ value_json.temp }}"
        availability_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:wall-sconce-round
      - name: "Groesses Aquarium I"
        unique_id: 1fcf004a-227a-4a77-86c4-ce3e15baeb0b
        command_topic: "shellies/shellyrgbw2-6CA20C/white/3/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/shellyrgbw2-6CA20C/white/3/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/shellyrgbw2-6CA20C/white/3/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/shellyrgbw2-6CA20C/white/3/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/shellyrgbw2-6CA20C/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:fish
      - name: "Groesses Aquarium II"
        unique_id: a7a2157d-37e1-44a2-a294-f78dd1dc72d3
        command_topic: "shellies/shellyrgbw2-6CA20C/white/2/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/shellyrgbw2-6CA20C/white/2/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/shellyrgbw2-6CA20C/white/2/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/shellyrgbw2-6CA20C/white/2/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/shellyrgbw2-6CA20C/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:fish
      - name: "Deckenlampe"
        unique_id: eb23c2a4-5eb5-49ad-a564-ef88c4159a36
        command_topic: "shellies/deckenlampe_kombiniert/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/deckenlampe_kombiniert/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/deckenlampe_kombiniert/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/deckenlampe_kombiniert/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/deckenlampe_kombiniert/online"
        payload_available: "true"
        optimistic: true
        icon: mdi:lightbulb-group
      - name: "Deckenlampe 1"
        unique_id: 16360f4d-d972-4bbd-9d5f-f8d622e11cdd
        command_topic: "shellies/ShellyVintage-3494546E705F/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/ShellyVintage-3494546E705F/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyVintage-3494546E705F/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyVintage-3494546E705F/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/ShellyVintage-3494546E705F/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:lightbulb-variant
      - name: "Deckenlampe 2"
        unique_id: 20f38449-25d7-444a-9c98-cda533cccedb
        command_topic: "shellies/ShellyVintage-3494546EF4AC/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/ShellyVintage-3494546EF4AC/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyVintage-3494546EF4AC/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyVintage-3494546EF4AC/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/ShellyVintage-3494546EF4AC/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:lightbulb-variant
      - name: "Deckenlampe 3"
        unique_id: d87edf75-d51b-493c-a25f-d4b1bc9da883
        command_topic: "shellies/ShellyVintage-3494546EFDEC/light/0/set"
        payload_on: >-
          {"turn": "on"}
        payload_off: >-
          {"turn": "off"}
        state_topic: "shellies/ShellyVintage-3494546EFDEC/light/0/status"
        state_value_template: >-
          {% if value_json.ison %}{"turn": "on"}{% else %}{"turn": "off"}{% endif %}
        brightness_state_topic: "shellies/ShellyVintage-3494546EFDEC/light/0/status"
        brightness_scale: 100
        brightness_value_template: "{{ value_json.brightness }}"
        brightness_command_topic: "shellies/ShellyVintage-3494546EFDEC/light/0/set"
        brightness_command_template: "{ brightness: {{ value }} }"
        availability_topic: "shellies/ShellyVintage-3494546EFDEC/online"
        payload_available: "true"
        optimistic: false
        icon: mdi:lightbulb-variant
        
