apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant
data:
  known_devices.yaml: |

  automations.yaml: |

  configuration.yaml: |
    homeassistant:
      # Name of the location where Home Assistant is running
      name: Home
      # Location required to calculate the time the sun rises and sets
      latitude: 54.03272894278802
      longitude: 11.665036436474116
      # Impacts weather/sunrise data (altitude above sea level in meters)
      elevation: 1
      # metric for Metric, imperial for Imperial
      unit_system: metric
      time_zone: Europe/Berlin

    # Enables the frontend
    frontend:

    # Enables configuration UI
    config:

    #Enable support for mobile client
    mobile_app:

    lovelace:
      mode: storage
      # Add yaml dashboards
      dashboards:
        lovelace-yaml:
          mode: yaml
          title: YAML
          icon: mdi:script
          show_in_sidebar: true
          filename: ui-lovelace.yaml

    # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
    http:
      server_port: 8123
      use_x_forwarded_for: true
      trusted_proxies: 10.244.5.0/24

    # Checks for available updates
    # Note: This component will send some information about your system to
    # the developers to assist with development of Home Assistant.
    # For more information, please see:
    # https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
    updater:
      # Optional, allows Home Assistant developers to focus on popular components.
      # include_used_components: true

    # Discover some devices automatically
    discovery:

    # Allows you to issue voice commands from the frontend in enabled browsers
    conversation:

    # Enables support for tracking state changes over time
    history:

    # View all events in a logbook
    logbook:

    # Enables a map showing the location of tracked devices
    map:

    # Track the sun
    sun:

    # Allow diagnosing system problems
    system_health:

    # Text to speech
    tts:
      - platform: google_translate
        service_name: google_say

    #mqtt
    mqtt:
      broker: mosquitto-service
      port: 1883
      username: homeassistant
      password: password
      client_id: homeassistant_mqtt_integration
      discovery: true

    # Cloud
    cloud:

    media_player:
      - platform: androidtv
        name: Android TV 1
        host: 192.168.1.111

    light:
      - platform: mqtt
        name: "Kleine Schlafzimmerlampe"
        state_topic: "stat/kleine_schlafzimmerlampe/RESULT"
        value_template: "{{ value_json.POWER }}"
        command_topic: "cmnd/kleine_schlafzimmerlampe/POWER"
        availability_topic: "tele/kleine_schlafzimmerlampe/LWT"
        qos: 1
        payload_on: "ON"
        payload_off: "OFF"
        payload_available: "Online"
        payload_not_available: "Offline"
        retain: false
      - platform: mqtt
        name: "Große Schlafzimmerlampe"
        state_topic: "stat/sonoff_fan/RESULT"
        value_template: "{{ value_json.POWER1 }}"
        command_topic: "cmnd/sonoff_fan/POWER1"
        availability_topic: "tele/sonoff_fan/LWT"
        qos: 1
        payload_on: "ON"
        payload_off: "OFF"
        payload_available: "Online"
        payload_not_available: "Offline"
        retain: false
      - platform: mqtt
        name: "Wohnzimmerlampe"
        state_topic: "stat/wohnzimmer_fan/RESULT"
        value_template: "{{ value_json.POWER1 }}"
        command_topic: "cmnd/wohnzimmer_fan/POWER1"
        availability_topic: "tele/wohnzimmer_fan/LWT"
        qos: 1
        payload_on: "ON"
        payload_off: "OFF"
        payload_available: "Online"
        payload_not_available: "Offline"
        retain: false
      - platform: mqtt
        name: "Kleine Buerolampe"
        state_topic: "shellies/shellyplug-s-F8CC85/relay/0"
        command_topic: "shellies/shellyplug-s-F8CC85/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        retain: false
      - platform: mqtt
        name: "Janas Schreibtischlampe"
        state_topic: "shellies/shellyplug-s-169A3F/relay/0"
        command_topic: "shellies/shellyplug-s-169A3F/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        retain: false
      - platform: mqtt
        schema: template
        name: "LED"
        command_topic: "shellies/shellyrgbw2-6CA20C/color/0/set"
        state_topic: "shellies/shellyrgbw2-6CA20C/color/0/status"
        retain: false
        effect_list:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if red is defined and green is defined and blue is defined -%}
          , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
          {%- endif -%}
          {%- if white_value is defined -%}
          , "white": {{ white_value }}
          {%- endif -%}
          {%- if effect is defined -%}
          , "effect": {{ effect }}
          {%- endif -%}
          }
        command_off_template: '{"turn":"off"}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
        red_template: '{{ value_json.red }}'
        green_template: '{{ value_json.green }}'
        blue_template: '{{ value_json.blue }}'
        white_value_template: '{{ value_json.white }}'
        effect_template: '{{ value_json.effect }}'
        qos: 2
      - platform: mqtt
        schema: template
        name: "Andere Lampe"
        command_topic: "shellies/ShellyBulbDuo-66471E/light/0/set"
        state_topic: "shellies/ShellyBulbDuo-66471E/light/0/status"
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "brightness": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if white_value is defined and white_value > 0 -%}
          , "temp": {{(1000000/(white_value | int)) | round(0,floor)}}
          {%- endif -%}
          {%- if white_value == 0 -%}
          , "temp": 2800
          {%- endif -%}
          }
        command_off_template: '{"turn":"off"}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
        retain: false
      - platform: mqtt
        schema: template
        name: "Büro Lampe"
        command_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/set"
        state_topic: "shellies/ShellyBulbDuo-8CAAB55F678A/light/0/status"
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "brightness": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if white_value is defined and white_value > 0 -%}
          , "temp": {{(1000000/(white_value | int)) | round(0,floor)}}
          {%- endif -%}
          {%- if white_value == 0 -%}
          , "temp": 2800
          {%- endif -%}
          }
        command_off_template: '{"turn":"off"}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
        retain: false
      - platform: mqtt
        schema: template
        name: "Kugel Lampe"
        command_topic: "shellies/ShellyBulbDuo-8CAAB55F6363/light/0/set"
        state_topic: "shellies/ShellyBulbDuo-8CAAB55F6363/light/0/status"
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "brightness": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if white_value is defined and white_value > 0 -%}
          , "temp": {{(1000000/(white_value | int)) | round(0,floor)}}
          {%- endif -%}
          {%- if white_value == 0 -%}
          , "temp": 2800
          {%- endif -%}
          }
        command_off_template: '{"turn":"off"}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
        retain: false
      - platform: mqtt
        schema: template
        name: "Bunte Kugellampe"
        command_topic: "shellies/shellycolorbulb-8CAAB555E04D/color/0/set"
        state_topic: "shellies/shellycolorbulb-8CAAB555E04D/color/0/status"
        retain: false
        effect_list:
          - Weiß
          - Bund
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if red is defined and green is defined and blue is defined -%}
          , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
          {%- endif -%}
          {%- if white_value is defined -%}
          , "white": {{ white_value }}
          {%- endif -%}
          {%- if red is defined and green is defined and blue is defined -%}
          , "mode": "color"
          {%- elif effect is defined -%}
            {%- if effect == 'Weiß' -%}
            , "mode": "white"
            {%- endif -%}
            {%- if effect == 'Bund' -%}
            , "mode": "color"
            {%- endif -%}
          {%- else -%}
          , "mode": "white"
          {%- endif -%}
          }
        command_off_template: '{"turn":"off","mode": "color","effect": 0}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
        red_template: '{{ value_json.red }}'
        green_template: '{{ value_json.green }}'
        blue_template: '{{ value_json.blue }}'
        white_value_template: '{{ value_json.white }}'
        effect_template: '{{ value_json.effect }}'
        qos: 2
      - platform: mqtt
        schema: template
        name: "Nachtlicht"
        command_topic: "shellies/ShellyBulbDuo-D15C2D/light/0/set"
        state_topic: "shellies/ShellyBulbDuo-D15C2D/light/0/status"
        command_on_template: >
          {"turn": "on"
          {%- if brightness is defined -%}
          , "brightness": {{brightness | float | multiply(0.3922) | round(0)}}
          {%- endif -%}
          {%- if white_value is defined and white_value > 0 -%}
          , "temp": {{(1000000/(white_value | int)) | round(0,floor)}}
          {%- endif -%}
          {%- if white_value == 0 -%}
          , "temp": 2800
          {%- endif -%}
          }
        command_off_template: '{"turn":"off"}'
        state_template: "{% if value_json.ison %}on{% else %}off{% endif %}"
        brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
        retain: false
    switch:
      - platform: mqtt
        name: "Grosses Aquarium"
        state_topic: "shellies/shellyplug-s-79D80C/relay/0"
        command_topic: "shellies/shellyplug-s-79D80C/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        retain: false
      - platform: mqtt
        name: "Kleines Aquarium"
        state_topic: "shellies/shellyplug-s-7A3532/relay/0"
        command_topic: "shellies/shellyplug-s-7A3532/relay/0/command"
        payload_on: "on"
        payload_off: "off"
        retain: false
    fan:
      - platform: mqtt
        name: "Schlafzimmer Ventilator"
        command_topic: "cmnd/sonoff_fan/FanSpeed"
        speed_command_topic: "cmnd/sonoff_fan/FanSpeed"
        state_topic: "stat/sonoff_fan/RESULT"
        speed_state_topic: "stat/sonoff_fan/RESULT"
        state_value_template: >
          {% if value_json.FanSpeed is defined %}
            {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}1{%- endif %}
          {% else %}
            {% if states.fan.sonoff_fan.state == 'off' -%}0{%- elif states.fan.sonoff_fan.state == 'on' -%}1{%- endif %}
          {% endif %}
        speed_value_template: "{{ value_json.FanSpeed }}"
        availability_topic: tele/sonoff_fan/LWT
        payload_off: "0"
        payload_on: "1"
        payload_low_speed: "1"
        payload_medium_speed: "2"
        payload_high_speed: "2"
        payload_available: Online
        payload_not_available: Offline
        speeds:
          - off
          - low
          - medium
          - high
      - platform: mqtt
        name: "Wohnzimmer Ventilator"
        command_topic: "cmnd/wohnzimmer_fan/FanSpeed"
        speed_command_topic: "cmnd/wohnzimmer_fan/FanSpeed"
        state_topic: "stat/wohnzimmer_fan/RESULT"
        speed_state_topic: "stat/wohnzimmer_fan/RESULT"
        state_value_template: >
          {% if value_json.FanSpeed is defined %}
            {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}1{%- endif %}
          {% else %}
            {% if states.fan.wohnzimmer_fan.state == 'off' -%}0{%- elif states.fan.wohnzimmer_fan.state == 'on' -%}1{%- endif %}
          {% endif %}
        speed_value_template: "{{ value_json.FanSpeed }}"
        availability_topic: tele/wohnzimmer_fan/LWT
        payload_off: "0"
        payload_on: "1"
        payload_low_speed: "1"
        payload_medium_speed: "2"
        payload_high_speed: "2"
        payload_available: Online
        payload_not_available: Offline
        speeds:
          - off
          - low
          - medium
          - high

    google_assistant:
      project_id: hassio-integration-1e887
      expose_by_default: true
      exposed_domains:
        - light
        - switch
        - script
        - fan
        - binary_sensor
        - climate

    automation: !include automations.yaml

  ui-lovelace.yaml: |
    views:
      - badges: []
        cards:
          - type: entities
            entities:
              - entity: light.grosse_schlafzimmerlampe
              - entity: light.kleine_schlafzimmerlampe
              - entity: fan.schlafzimmer_ventilator
            title: Schlafzimmer
            state_color: true
          - type: entities
            entities:
              - entity: light.wohnzimmerlampe
              - entity: light.andere_lampe
              - entity: fan.wohnzimmer_ventilator
              - entity: switch.kleines_aquarium
              - entity: switch.grosses_aquarium
              - entity: binary_sensor.0x00124b002228ec04_contact
            title: Wohnzimmer
            state_color: true
          - entities:
              - entity: light.kleine_buerolampe
            show_header_toggle: false
            title: Büro
            type: entities
          - type: entities
            entities:
              - entity: light.janas_schreibtischlampe
            title: Janas Zimmer
            state_color: true
          - entities:
              - entity: light.led
            show_header_toggle: false
            title: Badezimmer
            type: entities
          - type: entities
            entities:
              - entity: light.nachtlicht
          - type: thermostat
            entity: climate.wohnzimmer_thermostat
        panel: false
        title: base
      - title: TV
        path: ''
        panel: false
        badges: []
        cards:
          - type: entity
            entity: media_player.android_tv_1
          - type: media-control
            entity: media_player.android_tv_1
      - title: Extra
        path: extra
        badges: []
        cards:
          - type: entities
            entities:
              - sensor.waschmaschine_vibration_action
              - sensor.waschmaschine_vibration_linkquality
              - sensor.waschmaschine_vibration_sensitivity
              - sensor.waschmaschine_vibration_strength
          - type: entities
            entities:
              - sensor.klingel_action
              - sensor.klingel_linkquality
              - sensor.klingel_sensitivity
              - sensor.klingel_strength
      - title: Test
        path: test
        panel: true
        badges: []
        cards: []
