apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/raspberrypi3-homeassistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: persistence
              mountPath: /config/
            - name: config-volume
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: config-volume
              mountPath: /config/automations.yaml
              subPath: automations.yaml
          resources:
            requests:
              memory: 75Mi
            limits:
              memory: 150Mi
      volumes:
        - name: config-volume
          configMap:
            name: home-assistant-config
        - name: persistence
          persistentVolumeClaim:
            claimName: nas-persitant-volume-claim

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
      name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home-assistant-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: home-assistant.cluster
      http:
        paths:
          - path: /
            backend:
              serviceName: home-assistant-service
              servicePort: 80
