apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-persistant-volume
  namespace: home-assistant
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenants claim
  storageClassName: nas
  accessModes:
    - ReadWriteOnce 
  nfs:
    server: 192.168.1.6 
    path: /volume1/persistent_storage
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nas-persitant-volume-claim
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 1Gi