apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pihole-daemon
  namespace: home-assistant
  labels:
    app: pihole
spec:
  template:
    metadata:
      labels:
        app: pihole
        name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - name: dns-udp
              containerPort: 53
              hostPort: 53
            - name: admin
              containerPort: 80
          env:
            - name: WEBPASSWORD
              value: admin
  selector:
    matchLabels:
      app: pihole
      name: pihole
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-service
  namespace: home-assistant
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: pihole
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: pi.hole
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-service
              servicePort: 80