apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-configmap
data:
  # Modify this to set any custom DNS entries
  02-custom.conf: |
    address=/pihole.cluster/192.168.1.10
    address=/node-red.cluster/192.168.1.10
    address=/node-red-test.cluster/192.168.1.10
    address=/home-assistant.cluster/192.168.1.10
    address=/mosquitto.cluster/192.168.1.10
    address=/synology.cluster/192.168.1.6
  whitelist.txt: |
    id.google.com
    googleadservices.com
    www.googleadservices.com
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    http://sysctl.org/cameleon/hosts
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt

