apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: home-assistant
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
          - containerPort: 80
            name: pihole-http
            protocol: TCP
          - containerPort: 53
            name: dns
            protocol: TCP
          - containerPort: 53
            name: dns-udp
            protocol: UDP
          - containerPort: 443
            name: pihole-ssl
            protocol: TCP
          - containerPort: 67
            name: client-udp
            protocol: UDP
          env:
            - name: WEBPASSWORD
              value: admin
---
kind: Service
apiVersion: v1
metadata:
  name: pihole-service
  namespace: home-assistant
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: pihole
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-dns-service
spec:
  selector:
    app: pihole
  ports:
    - protocol: UDP
      name: dns-udp
      port: 53
      targetPort: 53
    - name: client-udp
      port: 67
      protocol: UDP
      targetPort: 67
  type: NodePort
  sessionAffinity: None
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pihole-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: pi.hole
      http:
        paths:
          - path: /
            backend:
              serviceName: pihole-service
              servicePort: 80