---
- hosts: all
  tasks:
    - name: add kubeadm apt-key
      become: true
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add kubeadm apt repository
      become: true
      apt_repository:
        repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        state: present
        filename: kubeadm
        update_cache: yes

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: install kubeadm
      become: true
      apt:
        name: kubeadm
        state: present
        update_cache: yes
